version: '3.0'
services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data_dev:/var/lib/mysql
    env_file:
      - ./db/env/.env.development
