version: "3"
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: calendar
      MONGO_INITDB_ROOT_PASSWORD: calendar
      MONGO_INITDB_DATABASE: calendar
    ports:
      - "27017:27017"
